version: '3.8'
services:
  app:
    container_name: app
    build: .
    expose:
      - 5000
    networks:
     - docker-elk
   

  es:
    image: elasticsearch:6.8.23
    container_name: es
    networks:
     - docker-elk
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    depends_on:
      - app

  kibana:
    image: kibana:8.4.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
     - docker-elk
    depends_on:
      - es
  nginx:
    container_name: NGINX
    build: ./nginx
    networks:
     - docker-elk
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  nginx:
networks:
  docker-elk:
   driver: bridge